### ISSUE TITLE
Construccion de la ventana1 primera parte

### ISSUE THREAD

**Issue by YhoimerSalas** [YhoimerSalas/Clase9#1]
construir ventana1 y hacer el formulario para ingresar la información del cliente

**Comment by RoyerPineda** [comment]
hola, voy a encargarme de esta funcionalidad

**Comment by YhoimerSalas** [comment]
Listo, todo terminado.
revisar el nuevo issue para continuar en ventana1 con el formulario de registro de usuarios.
